version: '3.8'

services:
  # Backend Spring Boot
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: soldiers_backend
    ports:
      - "0.0.0.0:8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://177.203.121.234:15432/vendas_futebol
    restart: unless-stopped

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: soldiers_frontend
    ports:
      - "0.0.0.0:8084:8084"
    environment:
      - VITE_API_URL=http://177.203.121.234:8083
    depends_on:
      - backend
    restart: unless-stopped 