spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.100.109:15432/vendas_futebol}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:Eunaoseiasenha22}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: admin
      password: admin123

server:
  port: 8080

logging:
  level:
    com.soldiers: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.jdbc: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG 